package com.lixiang.ssm.entity;

import java.math.BigDecimal;
import java.util.Date;

public class Seckill {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seckill.id
     *
     * @mbg.generated Tue Dec 18 12:01:10 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seckill.goods_name
     *
     * @mbg.generated Tue Dec 18 12:01:10 CST 2018
     */
    private String goodsName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seckill.stock
     *
     * @mbg.generated Tue Dec 18 12:01:10 CST 2018
     */
    private Integer stock;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seckill.price
     *
     * @mbg.generated Tue Dec 18 12:01:10 CST 2018
     */
    private BigDecimal price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seckill.start_date
     *
     * @mbg.generated Tue Dec 18 12:01:10 CST 2018
     */
    private Date startDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seckill.end_date
     *
     * @mbg.generated Tue Dec 18 12:01:10 CST 2018
     */
    private Date endDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seckill.status
     *
     * @mbg.generated Tue Dec 18 12:01:10 CST 2018
     */
    private Byte status;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill
     *
     * @mbg.generated Tue Dec 18 12:01:10 CST 2018
     */
    public Seckill(Integer id, String goodsName, Integer stock, BigDecimal price, Date startDate, Date endDate, Byte status) {
        this.id = id;
        this.goodsName = goodsName;
        this.stock = stock;
        this.price = price;
        this.startDate = startDate;
        this.endDate = endDate;
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill
     *
     * @mbg.generated Tue Dec 18 12:01:10 CST 2018
     */
    public Seckill() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seckill.id
     *
     * @return the value of seckill.id
     *
     * @mbg.generated Tue Dec 18 12:01:10 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seckill.id
     *
     * @param id the value for seckill.id
     *
     * @mbg.generated Tue Dec 18 12:01:10 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seckill.goods_name
     *
     * @return the value of seckill.goods_name
     *
     * @mbg.generated Tue Dec 18 12:01:10 CST 2018
     */
    public String getGoodsName() {
        return goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seckill.goods_name
     *
     * @param goodsName the value for seckill.goods_name
     *
     * @mbg.generated Tue Dec 18 12:01:10 CST 2018
     */
    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName == null ? null : goodsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seckill.stock
     *
     * @return the value of seckill.stock
     *
     * @mbg.generated Tue Dec 18 12:01:10 CST 2018
     */
    public Integer getStock() {
        return stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seckill.stock
     *
     * @param stock the value for seckill.stock
     *
     * @mbg.generated Tue Dec 18 12:01:10 CST 2018
     */
    public void setStock(Integer stock) {
        this.stock = stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seckill.price
     *
     * @return the value of seckill.price
     *
     * @mbg.generated Tue Dec 18 12:01:10 CST 2018
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seckill.price
     *
     * @param price the value for seckill.price
     *
     * @mbg.generated Tue Dec 18 12:01:10 CST 2018
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seckill.start_date
     *
     * @return the value of seckill.start_date
     *
     * @mbg.generated Tue Dec 18 12:01:10 CST 2018
     */
    public Date getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seckill.start_date
     *
     * @param startDate the value for seckill.start_date
     *
     * @mbg.generated Tue Dec 18 12:01:10 CST 2018
     */
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seckill.end_date
     *
     * @return the value of seckill.end_date
     *
     * @mbg.generated Tue Dec 18 12:01:10 CST 2018
     */
    public Date getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seckill.end_date
     *
     * @param endDate the value for seckill.end_date
     *
     * @mbg.generated Tue Dec 18 12:01:10 CST 2018
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seckill.status
     *
     * @return the value of seckill.status
     *
     * @mbg.generated Tue Dec 18 12:01:10 CST 2018
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seckill.status
     *
     * @param status the value for seckill.status
     *
     * @mbg.generated Tue Dec 18 12:01:10 CST 2018
     */
    public void setStatus(Byte status) {
        this.status = status;
    }
}