package com.lixiang.ssm.dao;

import org.apache.ibatis.annotations.Param;

import com.lixiang.ssm.entity.Seckill;

public interface SeckillMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill
     *
     * @mbg.generated Tue Dec 18 12:01:10 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill
     *
     * @mbg.generated Tue Dec 18 12:01:10 CST 2018
     */
    int insert(Seckill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill
     *
     * @mbg.generated Tue Dec 18 12:01:10 CST 2018
     */
    int insertSelective(Seckill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill
     *
     * @mbg.generated Tue Dec 18 12:01:10 CST 2018
     */
    Seckill selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill
     *
     * @mbg.generated Tue Dec 18 12:01:10 CST 2018
     */
    int updateByPrimaryKeySelective(Seckill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill
     *
     * @mbg.generated Tue Dec 18 12:01:10 CST 2018
     */
    int updateByPrimaryKey(Seckill record);
    
    boolean subStock(@Param("id") int id,@Param("num") int num);
    
    
}